version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: my-cassandra
    hostname: cassandra
    ports:
      - "9042:9042"  # Puerto CQL para conexiones de cliente
    networks:
      - cassandra_network
    environment:
      - CASSANDRA_CLUSTER_NAME=myCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1

networks:
  cassandra_network:
    driver: bridge
