version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysqltask
    environment:
      MYSQL_ROOT_PASSWORD: Abc123
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: usuario
      MYSQL_PASSWORD: changeme
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
